main:
  estimation_dates:
    - '2022-01-01'
    - '2022-01-15'
    - '2022-02-01'
    - '2022-02-15'
    - '2022-03-01'
    - '2022-03-15'
    - '2022-04-01'
    - '2022-04-15'
    - '2022-05-01'
    - '2022-05-15'
    - '2022-06-01'
    - '2022-06-15'
    - '2022-07-01'
    - '2022-07-15'
    - '2022-08-01'
    - '2022-08-15'
    - '2022-09-01'
    - '2022-09-15'
    - '2022-10-01'
    - '2022-10-15'
    - '2022-11-01'
    - '2022-11-15'
    - '2022-12-01'
    - '2022-12-15'
  locations:
    - "USA"
    - "United Kingdom"
    - "Brazil"
    - "Australia"
    - "South Africa"
    - "Japan"
    - "Egypt"
    - "Panama"
    - "Trinidad and Tobago"
    - "Costa Rica"
    - "Hong King"
    - "Vietnam"
  models:
    - "GARW"
    - "FGA"
    - "Piantham"
    - 'MLR'
    - "naive"
